"""Human-readable validation report: reports/validation.md + reports/big_dipper.png."""
import json

import numpy as np

from . import config as C

SURFACE, INK, INK2, GRID = '#fcfcfb', '#0b0b0b', '#52514e', '#e4e3df'
MEMBER, OUTLIER = '#2a78d6', '#eb6834'          # categorical slots 1-2 (validated)
FIGURE = [('Dubhe', 'Merak'), ('Merak', 'Phecda'), ('Phecda', 'Megrez'), ('Megrez', 'Dubhe'),
          ('Megrez', 'Alioth'), ('Alioth', 'Mizar'), ('Mizar', 'Alkaid')]


def _gnomonic(ra, dec, ra0, dec0):
    ra, dec, ra0, dec0 = map(np.radians, (ra, dec, ra0, dec0))
    c = np.sin(dec0) * np.sin(dec) + np.cos(dec0) * np.cos(dec) * np.cos(ra - ra0)
    x = np.cos(dec) * np.sin(ra - ra0) / c
    y = (np.cos(dec0) * np.sin(dec) - np.sin(dec0) * np.cos(dec) * np.cos(ra - ra0)) / c
    return -np.degrees(x), np.degrees(y)                         # east to the left, as on the sky


def dipper_figure(res, path):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    sky = res['4_big_dipper']['sky_radec_deg']
    members = set(res['4_big_dipper']['member_dev_kms'])
    epochs = list(sky)
    ra0 = np.mean([v[0] for v in sky[epochs[0]].values()])
    dec0 = np.mean([v[1] for v in sky[epochs[0]].values()])
    fig, axes = plt.subplots(1, len(epochs), figsize=(12, 3.4), facecolor=SURFACE, sharex=True, sharey=True)
    for ax, ep in zip(axes, epochs):
        pts = {n: _gnomonic(*sky[ep][n], ra0, dec0) for n in sky[ep]}
        ax.set_facecolor(SURFACE)
        for a, b in FIGURE:
            ax.plot([pts[a][0], pts[b][0]], [pts[a][1], pts[b][1]], color='#9a9993', lw=1, zorder=1)
        for n, (x, y) in pts.items():
            col = MEMBER if n in members else OUTLIER
            ax.scatter([x], [y], s=64, color=col, edgecolor=SURFACE, linewidth=2, zorder=3)
            if ep == epochs[0] or n not in members:
                ax.annotate(n, (x, y), xytext=(5, 6), textcoords='offset points', fontsize=8.5, color=INK2)
        title = 'Today (measured)' if ep.startswith('0') else f'+{ep.replace(" kyr", ",000 years")} (simulated)'
        ax.set_title(title, fontsize=10.5, color=INK, loc='left')
        ax.grid(color=GRID, lw=0.6)
        ax.tick_params(colors=INK2, labelsize=8, length=0)
        for s in ax.spines.values():
            s.set_visible(False)
        ax.set_aspect('equal')
        ax.set_xlabel('degrees east ←   → west', fontsize=8.5, color=INK2)
    axes[0].set_ylabel('degrees', fontsize=8.5, color=INK2)
    from matplotlib.lines import Line2D
    h = [Line2D([], [], marker='o', ls='', color=MEMBER, markersize=8, label='Ursa Major moving group (5 stars)'),
         Line2D([], [], marker='o', ls='', color=OUTLIER, markersize=8, label='Dubhe and Alkaid')]
    fig.legend(handles=h, loc='upper right', frameon=False, fontsize=9, labelcolor=INK2, ncol=2)
    fig.suptitle('The Big Dipper falls apart', x=0.01, ha='left', fontsize=12.5, color=INK, weight='bold')
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    fig.savefig(path, dpi=150, facecolor=SURFACE)
    plt.close(fig)


def write():
    res = json.loads((C.REPORTS / 'validation.json').read_text())
    m = json.loads((C.OUT / 'manifest.json').read_text())
    dipper_figure(res, C.REPORTS / 'big_dipper.png')
    ok = lambda r: '**PASS**' if r['pass'] else '**FAIL**'
    c1, c2, c3, c4, c5 = (res[k] for k in ('1_sky_matches_cosmos', '2_barnards_star', '3_gliese_710',
                                           '4_big_dipper', '5_sun_orbit'))
    L = ['# Validation report', '',
         'Generated by `python -m cosmos_time.build`. Every check runs on the decoded, quantised files in '
         '`time/data/` (bit-identical to what the browser integrates) with the reference integrator. '
         'Pass criteria were fixed in the plan before any data was fetched.', '',
         '## Known-answer checks', '',
         '| # | Check | Result | Criterion | Verdict |', '|---|---|---|---|---|',
         f"| 1 | Sky at t = 0 vs Cosmos's {c1['n']} stars | {c1['found']}/{c1['n']} found; median offset "
         f"{c1['diagnosis']['median_sep_deg']}°, worst {c1['max_sep_deg']}° ({c1['worst']}) | {c1['criterion']} | {ok(c1)} |",
         f"| 2 | Barnard's Star | {c2['min_dist_ly']} ly at +{c2['t_years']:,} yr ({c2['calendar_year_CE']:,} CE) | {c2['criterion']} | {ok(c2)} |",
         f"| 3 | Gliese 710 | {c3['min_dist_pc']} pc ({c3['min_dist_au']:,} au) at +{c3['t_myr']} Myr | {c3['criterion']} | {ok(c3)} |",
         f"| 4 | Big Dipper | members within {max(c4['member_dev_kms'].values())} km/s; Dubhe {c4['outlier_dev_kms']['Dubhe']}, "
         f"Alkaid {c4['outlier_dev_kms']['Alkaid']} km/s away | {c4['criterion']} | {ok(c4)} |",
         f"| 5 | Sun's orbit | {c5['azimuthal_period_myr']} Myr (mean over 3 Gyr {c5['mean_azimuthal_period_myr_3gyr']}); "
         f"±{c5['vertical_amplitude_pc']} pc every {c5['vertical_period_myr']} Myr | {c5['criterion']} | {ok(c5)} |", '']
    if not c1['pass']:
        bad = [s for s in c1['stars'] if s['found'] and s['sep_deg'] > 0.02]
        L += ['### Why check 1 fails', '',
              f"All {c1['n']} stars are found and the median offset is {c1['diagnosis']['median_sep_deg']}°, but "
              f"{len(bad)} stars miss the 0.02° tolerance. For every one of them SIMBAD (an independent "
              "reference) agrees with this pipeline and disagrees with the coordinates hard-coded in "
              "`index.html`. These are errors in Cosmos's curated star table, not in the Gaia/Hipparcos data. "
              'The threshold was not relaxed; fixing them is a change to `index.html` and is left to the owner.', '',
              '| Star | Ours vs Cosmos | Ours vs SIMBAD | Cosmos vs SIMBAD |', '|---|---|---|---|']
        for s in sorted(bad, key=lambda s: -s['sep_deg']):
            L.append(f"| {s['name']} | {s['sep_deg']:.4f}° | {s.get('ours_vs_simbad_deg', float('nan')):.5f}° | "
                     f"{s.get('cosmos_vs_simbad_deg', float('nan')):.4f}° |")
        L.append('')
    L += ['![The Big Dipper today and 50,000 and 100,000 years from now](big_dipper.png)', '',
          f"Gliese 710 in straight-line motion would pass at {c3['straight_line_min_pc']} pc at "
          f"+{c3['straight_line_t_myr']} Myr; the Galactic tide moves it by "
          f"{abs(c3['min_dist_pc'] - c3['straight_line_min_pc']) * 206265:.0f} au. Published Gaia DR3 values span "
          '0.052 pc (de la Fuente Marcos 2022) to 0.064 pc (Bailer-Jones 2022).', '',
          '## Engineering checks', '', '| Check | Result | Criterion | Verdict |', '|---|---|---|---|']
    e = res['engineering']
    fa = e['force_table_accuracy']
    L.append(f"| Force table vs galpy | max relative error {fa['max_rel_err']:.1e} ({fa['n']} points) | < 1e-3 | {ok(fa)} |")
    en = e['energy']
    L.append(f"| Energy conservation, Sun | {max(en['max_rel_energy_error'].values()):.1e} | {en['criterion']} | {ok(en)} |")
    cv = e['convergence']['dt_vs_dt_over_2']['250 Myr']
    L.append(f"| dt = 0.1 vs 0.05 Myr at 250 Myr | Sun {cv['sun_pc']:.3f} pc, median star {cv['median_star_pc']:.3f} pc | "
             f"{e['convergence']['criterion']} | {ok(e['convergence'])} |")
    sl = e['straight_line']['by_time']
    L.append(f"| Integrated vs straight line | 0.1 Myr: {sl['0.1 Myr']['median_rel_to_motion']:.1e} of the motion; "
             f"1 Myr: {sl['1 Myr']['median_dev_pc']:.2f} pc; 5 Myr: {sl['5 Myr']['median_dev_pc']:.1f} pc "
             f"(≈{sl['1 Myr']['median_dev_over_tide_estimate']:.2f}× the tidal estimate at every span) | "
             f"{e['straight_line']['criterion']} | {ok(e['straight_line'])} |")
    rv = e['reversibility']
    L.append(f"| Reversibility (float64) | {rv['max_roundtrip_error_pc']:.1e} pc | {rv['criterion']} | {ok(rv)} |")
    st = m['stats']
    L += ['', 'Browser-side tests (`time/test/`): the JS float64 twin and the WebGPU float32 kernel are '
          'compared against fixtures from this integrator, and a deep-link determinism test checks that the '
          'settled state is bit-identical however the time was reached.', '',
          '## Data', '',
          f"* {m['count']:,} stars: {st['local']:,} nearest-first Gaia DR3, {st['disk']:,} disk sample, "
          f"{st['bright']:,} bright/named ({st['hipparcos']:,} of them from Hipparcos-2 + XHIP).",
          f"* {st['rv_none']} stars have no radial velocity anywhere and are integrated with RV = 0 (flagged).",
          f"* {m['precise_count']:,} stars stored at full float32 precision; {m['tracked_count']:,} tracked for labels and figures.",
          f"* Files: {m['total_bytes'] / 1e6:.1f} MB in total; "
          f"{sum(v for k, v in m['sizes'].items() if k.startswith('stars')) / 1e6:.1f} MB of star data load up front.",
          f"* Solar parameters (astropy `Galactocentric` {m['frame']['astropy_defaults']}): R0 = {m['frame']['R0_kpc']} kpc, "
          f"z☉ = {m['frame']['z_sun_pc']} pc, v☉ = {tuple(m['frame']['v_sun_kms'])} km/s.", '']
    # a literal | inside a cell (|z|, |ΔE/E|) would split the markdown table
    L = [l if not l.startswith('|') else '|' + '|'.join(c.replace('|', '\\|') for c in _cells(l)) + '|' for l in L]
    (C.REPORTS / 'validation.md').write_text('\n'.join(L))


def _cells(row):
    """split a table row on the separators we wrote (' | '), not on | inside text"""
    inner = row[1:-1] if row.endswith('|') else row[1:]
    if set(inner.replace('|', '')) <= set('-'):
        return inner.split('|')
    return [' ' + c.strip() + ' ' for c in inner.strip().split(' | ')]


if __name__ == '__main__':
    write()
